services:
  scheduler-react:
    container_name: scheduler-react
    build:
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
        VITE_VAPID_PUBLIC_KEY: ${VITE_VAPID_PUBLIC_KEY}
    ports:
      - 5173:5173
