import Kanban from './Kanban'

beforeEach(() => cy.viewport(1360, 560))

describe('<Kanban />', () => {
  // status
  describe('status', () => {
    describe('using mouse events', () => {
      // left to right mouse events
      it('drags "todo" one column to the right', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="status-todo"]')
          .as('todo')
          .invoke('index')
          .should('equal', 0)
        cy.get('[data-rbd-draggable-id="status-on hold"]')
          .as('on-hold')
          .invoke('index')
          .should('equal', 1)
        cy.drag(
          '[data-rbd-draggable-id="status-todo"] > .MuiPaper-elevation0',
          '[data-rbd-draggable-id="status-on hold"]'
        )
        cy.get('@todo').invoke('index').should('equal', 1)
        cy.get('@on-hold').invoke('index').should('equal', 0)
      })

      it('drags "todo" two columns to the right', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="status-todo"]')
          .as('todo')
          .invoke('index')
          .should('equal', 0)
        cy.get('[data-rbd-draggable-id="status-on hold"]')
          .as('on-hold')
          .invoke('index')
          .should('equal', 1)
        cy.get('[data-rbd-draggable-id="status-inprogress"]')
          .as('inprogress')
          .invoke('index')
          .should('equal', 2)
        cy.drag(
          '[data-rbd-draggable-id="status-todo"] > .MuiPaper-elevation0',
          '[data-rbd-draggable-id="status-inprogress"]'
        )
        cy.get('@todo').invoke('index').should('equal', 2)
        cy.get('@on-hold').invoke('index').should('equal', 0)
        cy.get('@inprogress').invoke('index').should('equal', 1)
      })

      it('drags "todo" all the way to the right', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="status-todo"]')
          .as('todo')
          .invoke('index')
          .should('equal', 0)
        cy.get('[data-rbd-draggable-id="status-on hold"]')
          .as('on-hold')
          .invoke('index')
          .should('equal', 1)
        cy.get('[data-rbd-draggable-id="status-inprogress"]')
          .as('inprogress')
          .invoke('index')
          .should('equal', 2)
        cy.get('[data-rbd-draggable-id="status-done"]')
          .as('done')
          .invoke('index')
          .should('equal', 3)
        cy.drag(
          '[data-rbd-draggable-id="status-todo"] > .MuiPaper-elevation0',
          '[data-rbd-draggable-id="status-done"]'
        )
        cy.get('@todo').invoke('index').should('equal', 3)
        cy.get('@on-hold').invoke('index').should('equal', 0)
        cy.get('@inprogress').invoke('index').should('equal', 1)
        cy.get('@done').invoke('index').should('equal', 2)
      })

      // right to left mouse events
      it('drags "done" one column to the left', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="status-done"]')
          .as('done')
          .invoke('index')
          .should('equal', 3)
        cy.get('[data-rbd-draggable-id="status-inprogress"]')
          .as('inprogress')
          .invoke('index')
          .should('equal', 2)
        cy.drag(
          '[data-rbd-draggable-id="status-done"] > .MuiPaper-elevation0',
          '[data-rbd-draggable-id="status-inprogress"]'
        )
        cy.get('@done').invoke('index').should('equal', 2)
        cy.get('@inprogress').invoke('index').should('equal', 3)
      })

      it('drags "done" two columns to the left', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="status-done"]')
          .as('done')
          .invoke('index')
          .should('equal', 3)
        cy.get('[data-rbd-draggable-id="status-inprogress"]')
          .as('inprogress')
          .invoke('index')
          .should('equal', 2)
        cy.get('[data-rbd-draggable-id="status-on hold"]')
          .as('on-hold')
          .invoke('index')
          .should('equal', 1)
        cy.drag(
          '[data-rbd-draggable-id="status-done"] > .MuiPaper-elevation0',
          '[data-rbd-draggable-id="status-on hold"]'
        )
        cy.get('@done').invoke('index').should('equal', 1)
        cy.get('@inprogress').invoke('index').should('equal', 3)
        cy.get('@on-hold').invoke('index').should('equal', 2)
      })

      it('drags "done" all the way to the left', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="status-done"]')
          .as('done')
          .invoke('index')
          .should('equal', 3)
        cy.get('[data-rbd-draggable-id="status-inprogress"]')
          .as('inprogress')
          .invoke('index')
          .should('equal', 2)
        cy.get('[data-rbd-draggable-id="status-on hold"]')
          .as('on-hold')
          .invoke('index')
          .should('equal', 1)
        cy.get('[data-rbd-draggable-id="status-todo"]')
          .as('todo')
          .invoke('index')
          .should('equal', 0)
        cy.drag(
          '[data-rbd-draggable-id="status-done"] > .MuiPaper-elevation0',
          '[data-rbd-draggable-id="status-todo"]'
        )
        cy.get('@done').invoke('index').should('equal', 0)
        cy.get('@inprogress').invoke('index').should('equal', 3)
        cy.get('@on-hold').invoke('index').should('equal', 2)
        cy.get('@todo').invoke('index').should('equal', 1)
      })
    })

    describe('using keyboard events', () => {
      // left to right keyboard events
      it('drags "todo" one column to the right', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="status-todo"]')
          .as('todo')
          .invoke('index')
          .should('equal', 0)
        cy.get('[data-rbd-draggable-id="status-on hold"]')
          .as('on-hold')
          .invoke('index')
          .should('equal', 1)
        cy.get('[data-rbd-draggable-id="status-todo"] > .MuiPaper-elevation0')
          .focus()
          .type(' {rightArrow} ')
        cy.get('@todo').invoke('index').should('equal', 1)
        cy.get('@on-hold').invoke('index').should('equal', 0)
      })

      it('drags "todo" two columns to the right', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="status-todo"]')
          .as('todo')
          .invoke('index')
          .should('equal', 0)
        cy.get('[data-rbd-draggable-id="status-on hold"]')
          .as('on-hold')
          .invoke('index')
          .should('equal', 1)
        cy.get('[data-rbd-draggable-id="status-inprogress"]')
          .as('inprogress')
          .invoke('index')
          .should('equal', 2)
        cy.get('[data-rbd-draggable-id="status-todo"] > .MuiPaper-elevation0')
          .focus()
          .type(' {rightArrow}{rightArrow} ')
        cy.get('@todo').invoke('index').should('equal', 2)
        cy.get('@on-hold').invoke('index').should('equal', 0)
        cy.get('@inprogress').invoke('index').should('equal', 1)
      })

      it('drags "todo" all the way to the right', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="status-todo"]')
          .as('todo')
          .invoke('index')
          .should('equal', 0)
        cy.get('[data-rbd-draggable-id="status-on hold"]')
          .as('on-hold')
          .invoke('index')
          .should('equal', 1)
        cy.get('[data-rbd-draggable-id="status-inprogress"]')
          .as('inprogress')
          .invoke('index')
          .should('equal', 2)
        cy.get('[data-rbd-draggable-id="status-done"]')
          .as('done')
          .invoke('index')
          .should('equal', 3)
        cy.get('[data-rbd-draggable-id="status-todo"] > .MuiPaper-elevation0')
          .focus()
          .type(' {rightArrow}{rightArrow}{rightArrow} ')
        cy.get('@todo').invoke('index').should('equal', 3)
        cy.get('@on-hold').invoke('index').should('equal', 0)
        cy.get('@inprogress').invoke('index').should('equal', 1)
        cy.get('@done').invoke('index').should('equal', 2)
      })

      // right to left keyboard events
      it('drags "done" one column to the left', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="status-done"]')
          .as('done')
          .invoke('index')
          .should('equal', 3)
        cy.get('[data-rbd-draggable-id="status-inprogress"]')
          .as('inprogress')
          .invoke('index')
          .should('equal', 2)
        cy.get('[data-rbd-draggable-id="status-done"] > .MuiPaper-elevation0')
          .focus()
          .type(' {leftArrow} ')
        cy.get('@done').invoke('index').should('equal', 2)
        cy.get('@inprogress').invoke('index').should('equal', 3)
      })

      it('drags "done" two columns to the left', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="status-done"]')
          .as('done')
          .invoke('index')
          .should('equal', 3)
        cy.get('[data-rbd-draggable-id="status-inprogress"]')
          .as('inprogress')
          .invoke('index')
          .should('equal', 2)
        cy.get('[data-rbd-draggable-id="status-on hold"]')
          .as('on-hold')
          .invoke('index')
          .should('equal', 1)
        cy.get('[data-rbd-draggable-id="status-done"] > .MuiPaper-elevation0')
          .focus()
          .type(' {leftArrow}{leftArrow} ')
        cy.get('@done').invoke('index').should('equal', 1)
        cy.get('@inprogress').invoke('index').should('equal', 3)
        cy.get('@on-hold').invoke('index').should('equal', 2)
      })

      it('drags "done" all the way to the left', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="status-done"]')
          .as('done')
          .invoke('index')
          .should('equal', 3)
        cy.get('[data-rbd-draggable-id="status-inprogress"]')
          .as('inprogress')
          .invoke('index')
          .should('equal', 2)
        cy.get('[data-rbd-draggable-id="status-on hold"]')
          .as('on-hold')
          .invoke('index')
          .should('equal', 1)
        cy.get('[data-rbd-draggable-id="status-todo"]')
          .as('todo')
          .invoke('index')
          .should('equal', 0)
        cy.get('[data-rbd-draggable-id="status-done"] > .MuiPaper-elevation0')
          .focus()
          .type(' {leftArrow}{leftArrow}{leftArrow} ')
        cy.get('@done').invoke('index').should('equal', 0)
        cy.get('@inprogress').invoke('index').should('equal', 3)
        cy.get('@on-hold').invoke('index').should('equal', 2)
        cy.get('@todo').invoke('index').should('equal', 1)
      })
    })
  })

  // issue
  describe('issue', () => {
    // mouse events
    describe('using mouse events', () => {
      it('drags issue to the top', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="issue-Adjust column titles"]')
          .as('top-issue')
          .invoke('index')
          .should('equal', 0)
        cy.get('[data-rbd-draggable-id="issue-Create your own issues"]')
          .as('middle-issue')
          .invoke('index')
          .should('equal', 1)
        cy.get(
          '[data-rbd-draggable-id="issue-Get familiar with the kanban board"]'
        )
          .as('bottom-issue')
          .invoke('index')
          .should('equal', 2)
        cy.drag(
          '[data-rbd-draggable-id="issue-Get familiar with the kanban board"]',
          '[data-rbd-draggable-id="issue-Create your own issues"]'
        )
        cy.get('@top-issue').invoke('index').should('equal', 0)
        cy.get('@middle-issue').invoke('index').should('equal', 2)
        cy.get('@bottom-issue').invoke('index').should('equal', 1)
        cy.drag(
          '[data-rbd-draggable-id="issue-Get familiar with the kanban board"]',
          '[data-rbd-draggable-id="issue-Adjust column titles"]'
        )
        cy.get('@top-issue').invoke('index').should('equal', 1)
        cy.get('@middle-issue').invoke('index').should('equal', 2)
        cy.get('@bottom-issue').invoke('index').should('equal', 0)
      })

      it('drags issue to the bottom', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="issue-Adjust column titles"]')
          .as('top-issue')
          .invoke('index')
          .should('equal', 0)
        cy.get('[data-rbd-draggable-id="issue-Create your own issues"]')
          .as('middle-issue')
          .invoke('index')
          .should('equal', 1)
        cy.get(
          '[data-rbd-draggable-id="issue-Get familiar with the kanban board"]'
        )
          .as('bottom-issue')
          .invoke('index')
          .should('equal', 2)
        cy.drag(
          '[data-rbd-draggable-id="issue-Adjust column titles"]',
          '[data-rbd-draggable-id="issue-Create your own issues"]'
        )
        cy.get('@top-issue').invoke('index').should('equal', 1)
        cy.get('@middle-issue').invoke('index').should('equal', 0)
        cy.get('@bottom-issue').invoke('index').should('equal', 2)
        cy.drag(
          '[data-rbd-draggable-id="issue-Adjust column titles"]',
          '[data-rbd-draggable-id="issue-Get familiar with the kanban board"]'
        )
        cy.get('@top-issue').invoke('index').should('equal', 2)
        cy.get('@middle-issue').invoke('index').should('equal', 0)
        cy.get('@bottom-issue').invoke('index').should('equal', 1)
      })

      it('drags issue over statuses', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="issue-Adjust column titles"]')
          .as('top-issue')
          .invoke('index')
          .should('equal', 0)
        cy.get('[data-rbd-draggable-id="issue-Create your own issues"]')
          .as('middle-issue')
          .invoke('index')
          .should('equal', 1)
        cy.get(
          '[data-rbd-draggable-id="issue-Get familiar with the kanban board"]'
        )
          .as('bottom-issue')
          .invoke('index')
          .should('equal', 2)
        cy.get('[data-rbd-draggable-id="status-todo"]')
          .children()
          .last()
          .as('todo-issues')
          .children()
          .should('have.length', 3)
        cy.get('[data-rbd-draggable-id="status-on hold"]')
          .children()
          .last()
          .as('on-hold-issues')
          .children()
          .should('have.length', 0)
        cy.get('[data-rbd-draggable-id="status-inprogress"]')
          .children()
          .last()
          .as('inprogress-issues')
          .children()
          .should('have.length', 0)
        cy.get('[data-rbd-draggable-id="status-done"]')
          .children()
          .last()
          .as('done-issues')
          .children()
          .should('have.length', 0)
        cy.drag(
          '[data-rbd-draggable-id="issue-Adjust column titles"]',
          '[data-rbd-draggable-id="status-on hold"] > .MuiPaper-root'
        )
        cy.get('@todo-issues').children().should('have.length', 2)
        cy.get('@on-hold-issues').children().should('have.length', 1)
        cy.get('@inprogress-issues').children().should('have.length', 0)
        cy.get('@done-issues').children().should('have.length', 0)
        cy.drag(
          '[data-rbd-draggable-id="issue-Create your own issues"]',
          '[data-rbd-draggable-id="status-inprogress"] > .MuiPaper-root'
        )
        cy.get('@todo-issues').children().should('have.length', 1)
        cy.get('@on-hold-issues').children().should('have.length', 1)
        cy.get('@inprogress-issues').children().should('have.length', 1)
        cy.get('@done-issues').children().should('have.length', 0)
        cy.drag(
          '[data-rbd-draggable-id="issue-Get familiar with the kanban board"]',
          '[data-rbd-draggable-id="status-done"] > .MuiPaper-root'
        )
        cy.get('@todo-issues').children().should('have.length', 0)
        cy.get('@on-hold-issues').children().should('have.length', 1)
        cy.get('@inprogress-issues').children().should('have.length', 1)
        cy.get('@done-issues').children().should('have.length', 1)
        cy.drag(
          '[data-rbd-draggable-id="issue-Adjust column titles"]',
          '[data-rbd-draggable-id="status-todo"] > .MuiPaper-root'
        )
        cy.get('@todo-issues').children().should('have.length', 1)
        cy.get('@on-hold-issues').children().should('have.length', 0)
        cy.get('@inprogress-issues').children().should('have.length', 1)
        cy.get('@done-issues').children().should('have.length', 1)
      })
    })

    // keyboard events
    describe('using keyboard events', () => {
      it('drags issue to the top', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="issue-Adjust column titles"]')
          .as('top-issue')
          .invoke('index')
          .should('equal', 0)
        cy.get('[data-rbd-draggable-id="issue-Create your own issues"]')
          .as('middle-issue')
          .invoke('index')
          .should('equal', 1)
        cy.get(
          '[data-rbd-draggable-id="issue-Get familiar with the kanban board"]'
        )
          .as('bottom-issue')
          .invoke('index')
          .should('equal', 2)
        cy.get('@bottom-issue').focus().type(' {upArrow} ')
        cy.get('@top-issue').invoke('index').should('equal', 0)
        cy.get('@middle-issue').invoke('index').should('equal', 2)
        cy.get('@bottom-issue').invoke('index').should('equal', 1)
        cy.get('@bottom-issue').focus().type(' {upArrow}{upArrow} ')
        cy.get('@top-issue').invoke('index').should('equal', 1)
        cy.get('@middle-issue').invoke('index').should('equal', 2)
        cy.get('@bottom-issue').invoke('index').should('equal', 0)
      })

      it('drags issue to the bottom', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="issue-Adjust column titles"]')
          .as('top-issue')
          .invoke('index')
          .should('equal', 0)
        cy.get('[data-rbd-draggable-id="issue-Create your own issues"]')
          .as('middle-issue')
          .invoke('index')
          .should('equal', 1)
        cy.get(
          '[data-rbd-draggable-id="issue-Get familiar with the kanban board"]'
        )
          .as('bottom-issue')
          .invoke('index')
          .should('equal', 2)
        cy.get('@top-issue').focus().type(' {downArrow} ')
        cy.get('@top-issue').invoke('index').should('equal', 1)
        cy.get('@middle-issue').invoke('index').should('equal', 0)
        cy.get('@bottom-issue').invoke('index').should('equal', 2)
        cy.get('@top-issue').focus().type(' {downArrow}{downArrow} ')
        cy.get('@top-issue').invoke('index').should('equal', 2)
        cy.get('@middle-issue').invoke('index').should('equal', 0)
        cy.get('@bottom-issue').invoke('index').should('equal', 1)
      })

      it('drags issue over statuses', () => {
        cy.mount(<Kanban />)
        cy.get('[data-rbd-draggable-id="issue-Adjust column titles"]')
          .as('top-issue')
          .invoke('index')
          .should('equal', 0)
        cy.get('[data-rbd-draggable-id="issue-Create your own issues"]')
          .as('middle-issue')
          .invoke('index')
          .should('equal', 1)
        cy.get(
          '[data-rbd-draggable-id="issue-Get familiar with the kanban board"]'
        )
          .as('bottom-issue')
          .invoke('index')
          .should('equal', 2)
        cy.get('[data-rbd-draggable-id="status-todo"]')
          .children()
          .last()
          .as('todo-issues')
          .children()
          .should('have.length', 3)
        cy.get('[data-rbd-draggable-id="status-on hold"]')
          .children()
          .last()
          .as('on-hold-issues')
          .children()
          .should('have.length', 0)
        cy.get('[data-rbd-draggable-id="status-inprogress"]')
          .children()
          .last()
          .as('inprogress-issues')
          .children()
          .should('have.length', 0)
        cy.get('[data-rbd-draggable-id="status-done"]')
          .children()
          .last()
          .as('done-issues')
          .children()
          .should('have.length', 0)
        cy.get('@top-issue').focus().type(' {rightArrow} ')
        cy.get('@todo-issues').children().should('have.length', 2)
        cy.get('@on-hold-issues').children().should('have.length', 1)
        cy.get('@inprogress-issues').children().should('have.length', 0)
        cy.get('@done-issues').children().should('have.length', 0)
        cy.get('@middle-issue').focus().type(' {rightArrow}{rightArrow} ')
        cy.get('@todo-issues').children().should('have.length', 1)
        cy.get('@on-hold-issues').children().should('have.length', 1)
        cy.get('@inprogress-issues').children().should('have.length', 1)
        cy.get('@done-issues').children().should('have.length', 0)
        cy.get('@bottom-issue')
          .focus()
          .type(' {rightArrow}{rightArrow}{rightArrow} ')
        cy.get('@todo-issues').children().should('have.length', 0)
        cy.get('@on-hold-issues').children().should('have.length', 1)
        cy.get('@inprogress-issues').children().should('have.length', 1)
        cy.get('@done-issues').children().should('have.length', 1)
        cy.get('@top-issue').focus().type(' {leftArrow} ')
        cy.get('@todo-issues').children().should('have.length', 1)
        cy.get('@on-hold-issues').children().should('have.length', 0)
        cy.get('@inprogress-issues').children().should('have.length', 1)
        cy.get('@done-issues').children().should('have.length', 1)
      })
    })
  })
})
